import sys
import peppy
import glob

configfile: "config/config.yaml"

include: "rules/get_tidal.smk"
include: "rules/get_flybase.smk"
include: "rules/combined_te_ref.smk"
include: "rules/repeatmasker.smk"
include: "rules/salmon_idx.smk"
include: "rules/bwa_idx.smk"
include: "rules/bt1_idx.smk"


rule all:
    input:
        "results/tidal-anno/Tidalbase_transposon_sequence.dmel.fixed.consensus.gtf.gz",
        "results/flybase-anno/genome.fasta.gz",
        "results/repeatmasker/reference_insertions.bed",
        rules.combined_references.output,
        "results/salmon-idx/index/",
        "results/salmon-idx/transcripts_and_consensus_tes.aux.txt",
        "results/bwa_mem2-idx/idx.0123",
        "results/combined-anno/transcripts-plus-tes.tx2id.tsv",
        'results/bt1_unmasked-idx/'
#         "results/indices/vanilla_salmon_tes_transcripts/index/",
#         expand("results/indices/bwa_mem2/idx.{suf}",suf=["0123","amb","ann","bwt.2bit.64","pac"]),
#         "results/references/transcripts_and_consensus_tes/transcripts_and_consensus_tes.aux.txt",
#         "results/repeatmasker/reference_insertions.bed",
#         "results/overlaps/overlaps.tsv.gz",
#         "results/references/transcripts_and_consensus_tes/transcripts_and_consensus_tes.gtf",
#         



# include: "rules/resources.smk"
# include: "rules/references.smk"
# include: "rules/indices.smk"
# 
# include: "rules/feature_overlap.smk"
