# for getting TE sequences
TIDAL_ANNOTATION: https://github.com/laulabbrandeis/TIDAL/raw/master/annotation.tar.gz


# standard flybase references/resources
FULL_TRANSCRIPT_FASTA: http://ftp.flybase.net/releases/FB2021_04/dmel_r6.41/fasta/dmel-all-transcript-r6.41.fasta.gz # must be gz
MISCRNA_FASTA: http://ftp.flybase.net/releases/FB2021_04/dmel_r6.41/fasta/dmel-all-miscRNA-r6.41.fasta.gz
MIRNA_FASTA: http://ftp.flybase.net/releases/FB2021_04/dmel_r6.41/fasta/dmel-all-miRNA-r6.41.fasta.gz
NCRNA_FASTA: http://ftp.flybase.net/releases/FB2021_04/dmel_r6.41/fasta/dmel-all-ncRNA-r6.41.fasta.gz
TRNA_FASTA: http://ftp.flybase.net/releases/FB2021_04/dmel_r6.41/fasta/dmel-all-tRNA-r6.41.fasta.gz
PSEUDOGENE_FASTA: http://ftp.flybase.net/releases/FB2021_04/dmel_r6.41/fasta/dmel-all-pseudogene-r6.41.fasta.gz
GENOME_FASTA: http://ftp.flybase.net/releases/FB2021_04/dmel_r6.41/fasta/dmel-all-chromosome-r6.41.fasta.gz
TRANSCRIPTOME_GTF: http://ftp.flybase.net/releases/FB2021_04/dmel_r6.41/gtf/dmel-all-r6.41.gtf.gz


# Salmon indices for standard quantification approach
SALMON_K_PARAM: 31
# SALMON_VANILLA_USE_DECOYS: TRUE (deprecated: we now automatically use decoys)
